const works = [
  {
    title: 'Night Theater',
    year: '2017',
    medium: 'oil on canvas',
    height: '62',
    width: '100',
    img: '/assets/images/2017-night_theater-62x100.jpg',
  },
  {
    title: 'Group Portrait',
    year: '2017',
    medium: 'oil on canvas',
    height: '122',
    width: '82',
    img: '/assets/images/2017-group_portrait-122x82.JPG',
  },
  {
    title: 'La Chasse-galerie',
    year: '2017',
    medium: 'Charcoal',
    height: '30',
    width: '42',
    img: '/assets/images/2017-Chasse_Galerie-30x42.jpg',
  },
  {
    title: 'Born Free',
    year: '2017',
    medium: 'Charcoal',
    height: '30',
    width: '42',
    img: '/assets/images/2017-Born_Free-30x42.jpg',
  },
  {
    title: 'Omnomnom',
    year: '2017',
    medium: 'oil on canvas',
    height: '60',
    width: '42',
    img: '/assets/images/2017-om_nom_nom-60x42.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/IMG_4276.JPG',
  },
  {
    title: 'Maskerade Study I',
    year: '2016',
    medium: 'oil on canvas',
    height: '99',
    width: '64',
    img: '/assets/images/2016-maskerade_studie_I-99x64.jpg',
  },
  {
    title: 'Prolixe',
    year: '2016',
    medium: 'oil on panel',
    height: '40',
    width: '60',
    img: '/assets/images/2016-prolixe-40x60.jpg',
  },
  {
    title: 'Self-Portrait',
    year: '2016',
    medium: 'oil on canvas',
    height: '69',
    width: '50',
    img: '/assets/images/2016-self-portrait-69x50.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/SP1.JPG',
  },
  {
    title: 'Éclosion I',
    year: '2016',
    medium: 'oil on panel',
    height: '20',
    width: '20',
    img: '/assets/images/2016-éclosion_I-20x20.JPG',
  },
  {
    title: 'Éclosion II',
    year: '2016',
    medium: 'oil on panel',
    height: '20',
    width: '20',
    img: '/assets/images/2016-éclosion_II-20x20.JPG',
  },
  {
    title: 'Éclosion III',
    year: '2016',
    medium: 'oil on panel',
    height: '20',
    width: '20',
    img: '/assets/images/2016-éclosion_III-20x20.JPG',
  },
  {
    title: 'Anton',
    year: '2016',
    medium: 'oil on canvas',
    height: '140',
    width: '83',
    img: '/assets/images/2016-antonin-140x83.jpg',
  },
  {
    title: 'Gummy Bears',
    year: '2015',
    medium: 'oil on canvas',
    height: '42',
    width: '59',
    img: '/assets/images/2015-gummibaerchen-42x59.jpg',
  },
  {
    title: 'Gummy Study',
    year: '2015',
    medium: 'oil on panel',
    height: '20',
    width: '20',
    img: '/assets/images/2015-gummy-study.jpg',
  },
  {
    title: 'Cracked Eggs',
    year: '2015',
    medium: 'oil on canvas',
    height: '20',
    width: '30',
    img: '/assets/images/2015 cracked eggs.jpg',
  },
  {
    title: 'Three Horsemen and a Fool',
    year: '2016',
    medium: 'oil on canvas',
    height: '100',
    width: '147',
    img: '/assets/images/2016-three_horsemen_and_a_fool-100x147.jpg',
  },
  {
    title: 'Cleopatra',
    year: '2015',
    medium: 'oil on canvas',
    height: '69',
    width: '49',
    img: '/assets/images/2015-cleopatra-69x49.jpg',
  },
  {
    title: 'Jonah',
    year: '2014',
    medium: 'tempera on prepared paper',
    height: '40',
    width: '62',
    img: '/assets/images/2014-jonah_and_the_whale-40x62cm.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/Perseus study.JPG',
  },
  {
    title: 'Ginger Field',
    year: '2014',
    medium: 'oil on canvas',
    height: '122',
    width: '183',
    img: '/assets/images/2014-ginger_field-122x183.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/2017-sketchbook_p22.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/2017-sketchbook_p16.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/2017-sketchbook_p10.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/2017-sketchbook_p09.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/19512373_10211775041123598_456889378_n.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/19576349_10211775036043471_683281405_n.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/Alesso.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/Ana study.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/skull study.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/anatomy.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/crane.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/FishEyes.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/goya 1.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/goya 2.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/goya 3.jpg',
  },
  {
    description: ' ',
    img: '/assets/images/Head study of a man.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/IMG_4261.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/IMG_4259.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/IMG_4264.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/IMG_8183.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/IMG_8192.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/IMG_8199.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/Skeleton study.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/Standing nude sepia.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/Valerio.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/Voltaire charcoal.JPG',
  },
  {
    description: ' ',
    img: '/assets/images/Voltaire oil.JPG',
  }/*,
  {
    description: ' ',
    img: '',
  },
  {
    title: '',
    year: '',
    medium: '',
    height: '',
    width: '',
    img: '',
  }*/
];

export default works;
